# -*- coding: utf-8 -*-
"""nlpmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxVHDirCEpS_zO9up0_LFIbhOfTsFj95
"""

!pip install transformers
!pip install torch
!pip install diffusers
!pip install Pillow

from transformers import pipeline
from difflib import SequenceMatcher
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def summarize_text(text):
    # Split the text into manageable chunks for the model
    max_chunk = 1000
    text_chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]

    # Summarize each chunk
    summaries = [summarizer(chunk)[0]['summary_text'] for chunk in text_chunks]

    # Combine summaries into a single summary
    full_summary = " ".join(summaries)
    return full_summary

text = """
Molecular Structures
The stoichiometric formula (CH2O)n, where n is the number of carbons in the molecule represents carbohydrates. In other words, the ratio of carbon to hydrogen to oxygen is 1:2:1 in carbohydrate molecules. This formula also explains the origin of the term “carbohydrate”: the components are carbon (“carbo”) and the components of water (hence, “hydrate”). Scientists classify carbohydrates into three subtypes: monosaccharides, disaccharides, and polysaccharides.
Monosaccharides
Monosaccharides (mono- = “one”; sacchar- = “sweet”) are simple sugars, the most common of which is glucose. In monosaccharides, the number of carbons usually ranges from three to seven. Most monosaccharide names end with the suffix -ose. If the sugar has an aldehyde group (the functional group with the structure R-CHO), it is an aldose, and if it has a ketone group (the functional group with the structure RC(=O)R'), it is a ketose. Depending on the number of carbons in the sugar, they can be trioses (three carbons), pentoses (five carbons), and/or hexoses (six carbons). Figure 3.4 illustrates monosaccharides.
The molecular structures of glyceraldehyde, an aldose, and dihydroxyacetone, a ketose, are shown. Both sugars have a three-carbon backbone. Glyceraldehyde has a carbonyl group (c double bonded to O) at one end of the carbon chain with hydroxyl (OH) groups attached to the other carbons. Dihydroxyacetone has a carbonyl group in the middle of the chain and alcohol groups at each end. The molecular structures of linear forms of ribose, a pentose, and glucose, a hexose, are also shown. Both ribose and glucose are aldoses with a carbonyl group at the end of chain,and hydroxyl groups attached to the other carbons.
Figure 3.4 Scientists classify monosaccharides based on the position of their carbonyl group and the number of carbons in the backbone. Aldoses have a carbonyl group (indicated in green) at the end of the carbon chain, and ketoses have a carbonyl group in the middle of the carbon chain. Trioses, pentoses, and hexoses have three-, five-, and six- carbon backbones, respectively.
The chemical formula for glucose is C6H12O6. In humans, glucose is an important source of energy. During cellular respiration, energy releases from glucose, and that energy helps make adenosine triphosphate (ATP). Plants synthesize glucose using carbon dioxide and water, and glucose in turn provides energy requirements for the plant. Humans and other animals that feed on plants often obtain glucose from catabolized (cell breakdown of larger molecules) starch.
Galactose (part of lactose, or milk sugar) and fructose (found in sucrose, in fruit) are other common monosaccharides. Although glucose, galactose, and fructose all have the same chemical formula (C6H12O6), they differ structurally and chemically (and are isomers) because of the different arrangement of functional groups around the asymmetric carbon. All these monosaccharides have more than one asymmetric carbon (Figure 3.5).
VISUAL CONNECTION
The molecular structures of the linear forms of glucose, galactose, and fructose are shown. Glucose and galactose are both aldoses with a carbonyl group (carbon double-bonded to oxygen) at one end of the molecule. A hydroxyl (OH) group is attached to each of the other residues. In glucose, the hydroxyl group attached to the second carbon is on the left side of the molecular structure and all other hydroxyl groups are on the right. In galactose, the hydroxyl groups attached to the third and fourth carbons are on the left, and the hydroxyl groups attached to the second, fifth and sixth carbon are on the right. Frucose is a ketose with C doubled bonded to O at the second carbon. All other carbons have hydroxyl groups associated with them. The hydroxyl group associated with the third carbon is on the left, and all the other hydroxyl groups are on the right.
Figure 3.5 Glucose, galactose, and fructose are all hexoses. They are structural isomers, meaning they have the same chemical formula (C6H12O6) but a different atom arrangement.
What kind of sugars are these, aldose or ketose?
Glucose, galactose, and fructose are isomeric monosaccharides (hexoses), meaning they have the same chemical formula but have slightly different structures. Glucose and galactose are aldoses, and fructose is a ketose.
Monosaccharides can exist as a linear chain or as ring-shaped molecules. In aqueous solutions they are usually in ring forms (Figure 3.6). Glucose in a ring form can have two different hydroxyl group arrangements (OH) around the anomeric carbon (carbon 1 that becomes asymmetric in the ring formation process). If the hydroxyl group is below carbon number 1 in the sugar, it is in the alpha (α) position, and if it is above the plane, it is in the beta (β) position.
The conversion of glucose between linear and ring forms is shown. The glucose ring has five carbons and an oxygen. In alpha glucose, the first hydroxyl group is locked in a down position, and in beta glucose, the ring is locked in an up position. Structures for ring forms of ribose and fructose are also shown. Both sugars have a ring with four carbons and an oxygen.
Figure 3.6 Five and six carbon monosaccharides exist in equilibrium between linear and ring forms. When the ring forms, the side chain it closes on locks into an α or β position. Fructose and ribose also form rings, although they form five-membered rings as opposed to the six-membered ring of glucose.
Disaccharides
Disaccharides (di- = “two”) form when two monosaccharides undergo a dehydration reaction (or a condensation reaction or dehydration synthesis). During this process, one monosaccharide's hydroxyl group combines with another monosaccharide's hydrogen, releasing a water molecule and forming a covalent bond. A covalent bond forms between a carbohydrate molecule and another molecule (in this case, between two monosaccharides). Scientists call this a glycosidic bond (Figure 3.7). Glycosidic bonds (or glycosidic linkages) can be an alpha or beta type. An alpha bond is formed when the OH group on the carbon-1 of the first glucose is below the ring plane, and a beta bond is formed when the OH group on the carbon-1 is above the ring plane.
"""

summary = summarize_text(text)

# Summarize the text
#summary = summarizer(text, max_length=50, min_length=25, do_sample=False)
print(summary)

"""extracting keywords from summary"""

ner = pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english")

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def extract_keywords_tfidf(text, n_keywords=5):
    # Initialize TF-IDF vectorizer
    tfidf_vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')

    # Fit and transform the text
    tfidf_matrix = tfidf_vectorizer.fit_transform([text])

    # Get feature names
    feature_names = np.array(tfidf_vectorizer.get_feature_names_out())

    # Get TF-IDF scores for each feature (word)
    tfidf_scores = tfidf_matrix.toarray().flatten()

    # Sort indices by TF-IDF scores in descending order
    top_indices = tfidf_scores.argsort()[::-1][:n_keywords]

    # Get top keywords
    keywords = feature_names[top_indices]

    return keywords.tolist()

keywords = extract_keywords_tfidf(text)
print(keywords)

"""generate text prompts"""

def generate_prompts(keywords):
    prompts = []
    for keyword in keywords:
        prompt = f"Create an image of {keyword}"
        prompts.append(prompt)
    return prompts

prompts = generate_prompts(keywords)
for prompt in prompts:
    print(prompt)